### ISSUE TITLE
funkcija za uvoz

### ISSUE THREAD

**Issue by LonjaTT** [LonjaTT/APPR-2015-16#2]
mene pa zanima kje sem se zmotila pri funkciji za  uvoz: 
uvozi.stevilomuzejev <-function(){return(read.table("podatki/stmuzejevinrazbg.csv", row.names=1, col.names = regije))}
ko zaženem mi napiše to:
 Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  line 1 did not have 13 elements

**Comment by jaanos** [comment]
Če ne vidim podatkov, težko povem, kje je problem. Poskusi `read.table` nadomestiti z `read.csv` ali `read.csv2` (odvisno od tega, ali imaš med celicami vejico ali podpičje - to ločilo lahko sicer izrecno nastaviš s parametrom `sep`). Poglej tudi, ali imaš v datoteki CSV na začetku vrstice, v katerih ni podatkov. Če je tako, bo treba parameter `skip` nastaviti na število začetnih vrstic, ki naj se izpustijo.

Funkciji `read.csv` in `read.csv2` privzeto prvo (neizpuščeno) vrstico vzameta za glavo. Glede na to, da sama podajaš imena stolpcev, lahko nastaviš `header = FALSE` - seveda potem nastavi `skip` tako, da bo prva neizpuščena vrstica že vsabovala podatke.

Mimogrede, če pišeš kodo v issue (ali kamorkoli v Markdown), pred njo postavi vrstico

``````
```R
``````

za njo pa vrstico

``````
```
``````

Tako se bo koda ustrezno pobarvala (R je tukaj ime programskega jezika - po potrebi lahko uporabiš tudi kaj drugega). Na GitHubu imaš zavihek _Preview_, kjer si lahko pogledaš, kako bo izgledalo.
