### ISSUE TITLE
legenda pri grafu

### ISSUE THREAD

**Issue by LonjaTT** [LonjaTT/APPR-2015-16#4]
Pri grafu pri končni analizi podakov imam problem pri legendi. Ne vem kako naj jo postavim, da ne bo prekrivala grafa. 
Potem me pa zanima še, če obstaja kakšen način, da bi lahko poimenovala tudi tabele s podatki, ki jih potem uvozim.

**Comment by jaanos** [comment]
Najprej bi te opozoril, da ti uvoz trenutno ne deluje, saj imaš zakomentirane nekatere funkcije za uvoz, ki jih uporabljaš. Poleg tega se sklicuješ na neobstoječo spremenljivko `muzejiinrazstavisca` (najbrž si hotela uporabiti `muzeji`).

Graf raje nariši z ggplot2, saj tako ne bo potrebno vsega risati na roke. Pred tem bo potrebno podatke pretvoriti v obliko tidy data:

``` R
obiskovalci.tidy <- data.frame(leto = rownames(OK.obiskovalci),
                               OK.obiskovalci) %>%
  melt(variable.name = "regija", value.name = "stevilo")

ggplot(obiskovalci.tidy, aes(x = leto, y = stevilo,
                             group = regija, color = regija)) +
  geom_line() + geom_point() + ggtitle("Obiskovalci") +
  xlab("Leta") + ylab("Skupaj")
```

Če bi želela sama nastaviti uporabljene barve, lahko grafu prišteješ še `scale_color_manual(values = plot_colors)` (pri tem lahko barvam v vektorju `plot_colors` nastaviš kot imena imena regij, da bo res želena regija narisana z izbrano barvo). Če bi želela spreminjati izgled ostalih elementov grafa, lahko to dosežeš s funkcijo `theme` (poglej si pomoč zanjo).

Kaj natanko misliš s tem, da bi poimenovala tabele s podatki?

**Comment by LonjaTT** [comment]
Poimenovanje je bilo mišljeno predvsem, da bi pod tabelo ali sliko pisalo: tabela 1: prikazuje....

**Comment by jaanos** [comment]
Za tabele imaš že narejeno - pri ukazu `kable` uporabi parameter `caption`. Za grafe podaja parametra `fig.align` in `fig.cap` v glavi bloka kode, kjer prikazuješ graf.
