### ISSUE TITLE
Oddaja projekta

### ISSUE THREAD

**Issue by LonjaTT** [LonjaTT/APPR-2015-16#6]
Rada bi oddala svoj projekt.

**Comment by jaanos** [comment]
Se opravičujem za pozen odgovor, sem bil odsoten.

Poročila ti trenutno ne prevede, saj imaš pri ukazih `read.csv2` parameter `echo = FALSE`, ki pa tja ne sodi. Če se hočeš znebiti preostalih sporočil, v `projekt.Rmd` zraven tega parametra v glave lbokov kode dodaj še parametra `message = FALSE` in `warning = FALSE`.

Če se želiš sklicevati na slike, jih ne izrisuj v samih programih, pač pa v svojem bloku v poročilu, kjer tudi določiš besedilo pod njimi. Namesto, da v `analiza.r` torej kličeš `plot(graf)`, v `projekt.Rmd` na želeno mesto dodaj blok

``````
```{r graf, echo=FALSE, fig.align='center', fig.cap='Obiskovalci po regijah'}
plot(graf)
```
``````

Nanj se potem skličeš (kot se že) z `\ref{fig:graf}`, kjer oznaka za dvopičjem ustreza oznaki bloka. Podobno naredi tudi z ostalimi slikami.

**Comment by LonjaTT** [comment]
zdaj mi ne izpisuje več sporočil in tudi grafa in zemljevid mi nariše. ampak pri sklicevanju se mi še vedno pojavljajo vprašaji. In nad tabelami mi izpiše celo sporočilo `kable(head(....))`

**Comment by jaanos** [comment]
Ali lahko naložiš zadnjo verzijo na GitHub, da lahko pogledam, kaj se dogaja?
